### PR TITLE
Parser fix and syntax errors

### LINKED ISSUE #19: Fix parser error and  make syntax errors print in a better looking way

### PR DESCRIPTION
**Pull request by Wojzmuda**

### CODE REVIEW

File: TonSyntaxErrorListener.cpp [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+            expected = re.getExpectedTokens().toString(vocab);
+        } else {
+            expected = "Could not determine expected tokens (Invalid State)";
+        }
+    } catch (...) {
+
+    }
+}
+
+if (msg.find("mismatched input") != std::string::npos){
```
Comment (Wojzmuda) [inline TonSyntaxErrorListener.cpp:30]: there is an issue with it not showing what it expects, but i think we can leave it for now
